---
# Tasks for upgrading the core RogerOS services for a running cluster.
- hosts: machines
  serial: "100%"
  roles:
    - common
    - java

- hosts: zookeeper
  serial: 1
  roles:
    - zookeeper

- hosts: masters
  serial: 1
  roles:
    - mesos-common
    - mesos-master

- hosts: slaves
  serial: "10%"
  roles:
    - mesos-common
    - mesos-slave

- hosts: marathon_servers
  serial: 1
  roles:
    - marathon-server
    - chronos

- hosts: bamboo_servers
  serial: "10%"
  roles:
    - bamboo
